/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.util.ArrayList;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import static projet.menu_principal.h;

/**
 *
 * @author ASUS
 */
public class affichage_patients extends javax.swing.JInternalFrame {

    /**
     * Creates new form affichage_patients
     */
    public affichage_patients() { initComponents();
        //preparation des parametres de jtable
         String [] entetes =new String[]
        {
            "Cle_patient","Nom Prenom","Genre","Telephone","Date_naiss"
        };
         //on crée une matrice data ou on met le contenu du hashmap
          String [][] data=new String[100][100];
        int k=0;//k est un compteur de parcours du hashmap pour afficher les patients
          for (Map.Entry m : h.entrySet())
        {
            dossier_medical d=new dossier_medical();
            d=h.get(m.getKey());
            //selon les colonnes de 0 a 4 on affiche les attributs du patient
            //selon le k:nb_patients on affiche les clients
            data[k][0]=d.getClé();
            data[k][1]=d.getNom_prenom();
            data[k][2]=d.getGenre();
            data[k][3]=(d.getNb_tel()+"");
            data[k][4]=(d.getDate_nais().jour+"/"+d.getDate_nais().mois+"/"+d.getDate_nais().année);
            k++;//k est un compteur de parcours du hashmap pour afficher les patients 
        } //jtable prend la matrice data comme parametre pr l'afficher
         JTable.setModel(new DefaultTableModel(data,entetes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        JTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        JTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nom_Prenom", "Genre", "Telephone", "Date_naiss"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTable.setToolTipText("");
        jScrollPane3.setViewportView(JTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTable;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
