/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static projet.menu_principal.h;

/**
 *
 * @author ASUS
 */
public class affichage_consultation extends javax.swing.JInternalFrame {

    /**
     * Creates new form affichage_consultation
     */
    public affichage_consultation() {
        initComponents();
        String [] entetes =new String[]
        {
            "Cle_patient","Date Consultation","Diagnostic","Prescription"
        };
         //on crée une matrice data ou on met le contenu du hashmap
          String [][] data=new String[100][100];
          jTable1.setModel(new DefaultTableModel(data,entetes));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aff = new javax.swing.JButton();
        ctrl_ref = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setText("Affichage consultation:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Reference du Patient:");

        aff.setText("afficher consultations");
        aff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ref))
                        .addGap(32, 32, 32)
                        .addComponent(ctrl_ref, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 160, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ctrl_ref, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(19, 19, 19)
                .addComponent(aff)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refActionPerformed

    private void affActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affActionPerformed
        // TODO add your handling code here:
         
          String [] entetes =new String[]
        {
            "Cle_patient","Date_cons","diagnostic","analyse","act_radio","medicament","specialiste"
        };
         //on crée une matrice data ou on met le contenu du hashmap
          String [][] data=new String[100][100];
        int i=0;int test=0;
    try{
         if(ref.getText().equals(""))
        {
            ctrl_ref.setText(" ** saisir ref");
            ctrl_ref.setForeground(Color.red);
            i=1;
        }
          if(i==0)
          { 
                for (Map.Entry m : h.entrySet())
                {
                    String s=(String)m.getKey(); int n=h.get(m.getKey()).getTab().size();
                    if ((s.compareTo(ref.getText())==0))
                    { 
                  //mise du dossier medical recupéré dans une matrice
                    data[0][0] =ref.getText();
                    System.out.println(n);
                    for(int j=0;j<n;j++)
                    {
                         System.out.println(n);
                       data [j][1]=h.get(m.getKey()).getTab().get(j).getDate_cons().getJour()+"/"+h.get(m.getKey()).getTab().get(j).getDate_cons().getMois()+"/"+h.get(m.getKey()).getTab().get(j).getDate_cons().getAnnée();
                       data[j][2]=h.get(m.getKey()).getTab().get(j).getDiagnostic();
                       
                       for(int a=0;a<h.get(m.getKey()).getTab().get(j).getPrescription().size();a++)
                       {
                         if(h.get(m.getKey()).getTab().get(j).getPrescription().get(a).typepres()==1)
                        {data[j][3]=h.get(m.getKey()).getTab().get(j).getPrescription().get(a).retour();}
                               //
                         if(h.get(m.getKey()).getTab().get(j).getPrescription().get(a).typepres()==2)
                        {data[j][5]=h.get(m.getKey()).getTab().get(j).getPrescription().get(a).retour();}
                              //
                         if(h.get(m.getKey()).getTab().get(j).getPrescription().get(a).typepres()==3)
                        {data[j][6]=h.get(m.getKey()).getTab().get(j).getPrescription().get(a).retour();}
                           //
                         if(h.get(m.getKey()).getTab().get(j).getPrescription().get(a).typepres()==4)
                        {data[j][4]=h.get(m.getKey()).getTab().get(j).getPrescription().get(a).retour();}
                       }
                    }
                    }
                }
                    jTable1.setModel(new DefaultTableModel(data,entetes));
          }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"err incomp"+e.getMessage(),"erre",0 );}
          
          
    }//GEN-LAST:event_affActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aff;
    private javax.swing.JLabel ctrl_ref;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ref;
    // End of variables declaration//GEN-END:variables
}
