/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;
import projet.Act_radio;
import projet.Analyse;
import projet.Consultation;
import projet.Prescription;
import projet.affichage_consultation;
import projet.affichage_patients;
import projet.affichage_unique;
import projet.array;
import projet.consultation_frame;
import projet.date;
import projet.dossier_medical;
import projet.gestion_dossiers;
import projet.medicament;
import projet.specialiste;


/**
 *
 * @author ASUS
 */
public class menu_principal extends javax.swing.JFrame {
public static HashMap  <String, dossier_medical> h=new HashMap<String, dossier_medical>();
    /**
     * Creates new form menu_principal
     */

    public menu_principal() {
        h=new HashMap <String, dossier_medical> ();
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }
    static public void initialisation(){
            Prescription r1_1=new Analyse ("NFS");
            Prescription r1_2=new medicament ("Tardyferon",500);
            ArrayList <Prescription> p1=new ArrayList ();
            p1.add(r1_1);
            p1.add(r1_2);
            date dt1_cons=new date(25,12,2018);
        Consultation cs1=new Consultation(dt1_cons,"Anémie",p1);
        ArrayList <Consultation> c1= new ArrayList ();
        c1.add(cs1);
        
        date dt1_nais=new date (29,9,2000);
        dossier_medical d1=new dossier_medical("Patient1","Fendi Fadwa",dt1_nais,"femme",99126330,c1);
         h.put("Patient1", d1);
        
         //patient2
        Prescription r2_1=new Analyse ("Glycémie");
            Prescription r2_2=new specialiste ("Diabètologue","Frédéric Bosquet");
            ArrayList <Prescription> p2=new ArrayList <Prescription>();
            p2.add(r2_1);
            p2.add(r2_2);
            date dt2_cons=new date(13,02,2019);
        Consultation cs2=new Consultation(dt2_cons,"Diabète",p2);
        ArrayList <Consultation> c2= new ArrayList <Consultation>();
        c2.add(cs2);
        date dt2_nais=new date (4,11,2004);
        dossier_medical d2=new dossier_medical("Patient2","Malek Sassi",dt2_nais,"homme",98126335,c2);
        
        //ajout des deux patients dans HashMap
        h.put("Patient2", d2);
        
        //patient3
        Prescription r3_1=new Analyse ("Bilan Rénal");
            Prescription r3_2=new Act_radio ("Ecographie");
            ArrayList <Prescription> p3=new ArrayList <Prescription>();
            p3.add(r3_1);
            p3.add(r3_2);
            date dt3_cons=new date(20,4,2019);
        Consultation cs3=new Consultation(dt3_cons,"Insuffisance Rénale",p3);
        ArrayList <Consultation> c3= new ArrayList <Consultation>();
        c3.add(cs3);
        date dt3_nais=new date (5,9,1997);
        dossier_medical d3=new dossier_medical("Patient3","Jamil Mansour",dt3_nais,"homme",28187335,c3);
        //ajout des deux patients dans HashMap
        h.put("Patient3", d3);
        //patient4
        Prescription r4_1=new Analyse ("Glycémie");
            Prescription r4_2=new specialiste ("Ophtalmologue","Zouhair Chebbbi");
            ArrayList <Prescription> p4=new ArrayList <Prescription>();
            p4.add(r4_1);
            p4.add(r4_2);
            date dt4_cons=new date(1,7,2019);
        Consultation cs4=new Consultation(dt4_cons,"Diabète",p4);
        ArrayList <Consultation> c4= new ArrayList <Consultation>();
        c4.add(cs4);
        date dt4_nais=new date (5,2,1980);
        dossier_medical d4=new dossier_medical("Patient4","Moussa Nsir",dt4_nais,"homme",54187335,c4);
        h.put("Patient4", d4);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        operations = new javax.swing.JMenu();
        ajout_patient = new javax.swing.JMenuItem();
        ajout_consultation = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        tous = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Menu Principal"); // NOI18N

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 965, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 667, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));

        operations.setText("Patient");
        operations.setAutoscrolls(true);
        operations.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        ajout_patient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ajout_patient.setText("Ajout patient");
        ajout_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_patientActionPerformed(evt);
            }
        });
        operations.add(ajout_patient);

        ajout_consultation.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ajout_consultation.setText("Ajout consultation");
        ajout_consultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajout_consultationActionPerformed(evt);
            }
        });
        operations.add(ajout_consultation);

        jMenuBar1.add(operations);

        jMenu1.setText("Affichage");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Afficher un patient");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        tous.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tous.setText("Afficher tous les patients");
        tous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tousActionPerformed(evt);
            }
        });
        jMenu1.add(tous);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Afficher les consultations");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Afficher les Statistiques selon le genre");
        jMenuItem3.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jMenuItem3ComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jMenuItem3ComponentRemoved(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Afficher les statistiques des maladies ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajout_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_patientActionPerformed
        // TODO add your handling code here:
        initialisation();
        gestion_dossiers formul=new gestion_dossiers();
        desktop.add(formul);
        formul.show();
       
    }//GEN-LAST:event_ajout_patientActionPerformed

    private void ajout_consultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajout_consultationActionPerformed
        // TODO add your handling code here:
        initialisation();
        consultation_frame consultation=new consultation_frame();
       
        desktop.add(consultation);
        consultation.show();
        
    }//GEN-LAST:event_ajout_consultationActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        initialisation();
        affichage_unique x=new affichage_unique();
        desktop.add(x);
        x.show();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tousActionPerformed
        // TODO add your handling code here:
        initialisation();
         affichage_patients x=new affichage_patients();
        desktop.add(x);
        x.show();
      
    }//GEN-LAST:event_tousActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        initialisation();
         affichage_consultation x=new affichage_consultation();
        desktop.add(x);
        x.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    
        initialisation();
        Iterator i = h.entrySet().iterator();
     float s=0,f=0,h=0;
        while (i.hasNext()) {
            s++;
          Map.Entry mapentry = (Map.Entry) i.next();
          dossier_medical k=new dossier_medical();
          k=(dossier_medical)mapentry.getValue();
          if (k.getGenre().compareTo("femme")==0){
              f++;
          }
          else
              h++;
        } 

        DefaultPieDataset pieDataset =new DefaultPieDataset();
        pieDataset .setValue("Homme",new Float(h/s*100));
        pieDataset .setValue("Femme",new Float(f/s*100));
        JFreeChart chart= ChartFactory.createPieChart("Statistique de genres des patients", pieDataset, true, true, true);
        PiePlot P = (PiePlot)chart.getPlot();
        //P.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Statistiques",chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem3ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenuItem3ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ComponentAdded

    private void jMenuItem3ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenuItem3ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ComponentRemoved

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
       initialisation();
        
        Iterator i = h.entrySet().iterator();
     
     int s=0,f;
     ArrayList<array> l=new ArrayList <array>(4); 

        for (Map.Entry mapentry : h.entrySet()) {
            int x=0;
            boolean test=false;
            f=1;
              dossier_medical k;
          k=(dossier_medical)mapentry.getValue();
          Consultation c;
          c=(Consultation)k.getTab().get(0);
          array a = new array();
          a.setMaladie(c.getDiagnostic());
          a.setNb(1);
         
                  l.add(a);
          x++;
          }
        
        System.out.println(l.size()+"\n");
        for (int y=0;y<l.size();y++){
            System.out.println(l.get(y).getMaladie());
            System.out.println(l.get(y).getNb()+"\n");
        }

        DefaultPieDataset pieDataset =new DefaultPieDataset();
        for (int y=0;y<l.size();y++)
        {
        pieDataset .setValue((String)l.get(y).getMaladie(),new Integer(l.get(y).getNb()));
        }
        JFreeChart chart= ChartFactory.createPieChart("Statistique des maladies", pieDataset, true, true, true);
        PiePlot P = (PiePlot)chart.getPlot();
        ChartFrame frame = new ChartFrame("Statistiques",chart);
        frame.setVisible(true);
        frame.setSize(450,500);
        
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //h.add(d)
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>*/

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_principal().setVisible(true);
            }
            
        }); 
        initialisation();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajout_consultation;
    private javax.swing.JMenuItem ajout_patient;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu operations;
    private javax.swing.JMenuItem tous;
    // End of variables declaration//GEN-END:variables
}
